### ISSUE TITLE
VNF Descriptor creation

### ISSUE THREAD

**Issue by xilouris** [sonata-nfv/son-vcdn-pilot#5]
- [x] vTU VNFD (commit to GitHub) @javier-fh 
- [x] vCC VNFD (commit to GitHub)  @skolome @arocha7 
- [x] vTC VNFD (commit to GitHub) @skolome

**Comment by skolome** [comment]
Copied and created the VNFDs from D6.2 into the appropriate section. Review for any irregularities

**Comment by xilouris** [comment]
Please, during your VNFD refinements you need to make certain that the VNFD corresponds to the one that is currently operating in the SONATA.demo tenant.
